### ISSUE TITLE
Display on top of tabbar

### ISSUE THREAD

**Issue by CollinHemeltjen** [schmidyy/Loaf#14]
First of all, great and useful library here!

Currently when showing a Loaf inside a UITabBarController, the Loaf will display on top of the tabbar. Hereby interfering with the user interaction by blocking the buttons. 

Like this:
<img width="525" alt="LoafNow" src="https://user-images.githubusercontent.com/24717876/55644051-02e93800-57d5-11e9-9b0f-6f8453f54e48.png">

Can we make it an option to set the location above the tabbar?

Like so:
<img width="525" alt="LoafProposed" src="https://user-images.githubusercontent.com/24717876/55644068-0ed4fa00-57d5-11e9-984a-8030e8e00b19.png">

**Comment by schmidyy** [comment]
This is fixed as of https://github.com/schmidyy/Loaf/commit/09ce720ee64935a3ad6193e5693a6cdedb16fdb9 👍
