### ISSUE TITLE
Is there a way to adjust the size of the loaf?

### ISSUE THREAD

**Issue by isupremedyou** [schmidyy/Loaf#17]
Is it possible to adjust the height/width of the loaf? It looks like the width is hard coded as 200, but it would be nice to either override this, or if that is undesirable for some reason, perhaps it should be 0.8 of the view's width?

**Comment by schmidyy** [comment]
Interesting idea (80% of the view's width)! I suppose the fixed width, which was intended for phones, might look small on larger devices. 

I've update the `Style` component to optionally take a width as either a fixed value or a percentage of the screen width here: https://github.com/schmidyy/Loaf/commit/ba9af6773810bce05d757e6f9bedc9942df02e57
