### ISSUE TITLE
Add SPM Support!

### ISSUE THREAD

**Issue by toyinswift** [schmidyy/Loaf#23]
Kindly add SPM support and update ReadMe with correct version name

**Comment by ehlersd** [comment]
@schmidyy I see that the Package.swift file has been added, but we cannot use it until you create a new release...

Let me know if there's anything I can do to help...

**Comment by schmidyy** [comment]
Just created a GH release, let me know if everything works! @ehlersd

**Comment by ehlersd** [comment]
@schmidyy Worked perfectly!  Thx!
