### ISSUE TITLE
completionHandler stopped working

### ISSUE THREAD

**Issue by 64knl** [schmidyy/Loaf#3]
This example code from readme no longer works: 

        Loaf("Loaf message", sender: self, completionHandler: {
            print("Dismissal complete")
        }).show()

Error messages in xCode: 
1. Argument 'completionHandler' must precede argument 'sender'
2. Incorrect argument label in call (have '_:completionHandler:sender:', expected '_:state:sender:')

**Comment by schmidyy** [comment]
Hey, I should've posted an update. I've moved and renamed the completion handler in the 0.3.0. 

A completion handler can now be specified in the `show()` function.

```swift
Loaf(example.rawValue, sender: self).show {
       print("Dismissed!")
}
```

I'll update the README accordingly 🙂
