### ISSUE TITLE
Loaf 0.3 crashes app

### ISSUE THREAD

**Issue by 64knl** [schmidyy/Loaf#4]
This piece of code causes 'Thread 1: signal SIGABRT'

`Loaf( "message" , sender: self).show (.short, onTap: {
    print("Dismissal complete")
})`

**Comment by schmidyy** [comment]
Hmm, I can't reproduce the crash. Are you calling this from a `UIViewController`? @NotFoundDC

**Comment by schmidyy** [comment]
Out of curiosity, what is your project deployment target set to? 
<img width="665" alt="screen shot 2019-03-03 at 7 38 11 pm" src="https://user-images.githubusercontent.com/22358682/53704591-ecbe1580-3deb-11e9-97a0-5af24ab0c617.png">

**Comment by 64knl** [comment]
The deployment target for the project is 12.1. The previous release of Loaf worked perfectly (but it would crash the app when performing a segue before dismissal). I will try and see if I can find out whats causing the issue.

**Comment by 64knl** [comment]
OK, totally my fault. Sorry for wasting your time.
