### ISSUE TITLE
CocoaPod "Unable to find a specification for `Loaf`"

### ISSUE THREAD

**Issue by WingCH** [schmidyy/Loaf#7]
![image](https://user-images.githubusercontent.com/19588517/54083554-d968f800-435f-11e9-8ba5-47b7bef7be16.png)
![image](https://user-images.githubusercontent.com/19588517/54083556-df5ed900-435f-11e9-8297-e2791b80423c.png)

**Comment by schmidyy** [comment]
Hmm, I just tried with a fresh project and it seems to work for me.

![image](https://user-images.githubusercontent.com/22358682/54086243-101e1e80-431e-11e9-8686-eae8c72b1a35.png)
![image](https://user-images.githubusercontent.com/22358682/54086231-ff6da880-431d-11e9-9c08-385f0331079d.png)

----

Few things you could try:
- There might be a problem with how Cocoapods is setup on your machine. As per [this suggestion](https://stackoverflow.com/a/32850706/5811184), try running `pod setup` in your terminal.
- You could also try locking the pod version in your podfile by using `pod 'Loaf', '~> 0.3'` insteas of just `pod 'Loaf'`

Let me know how it goes!

**Comment by 64knl** [comment]
You need to update the Pods to see Loaf. 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/3864423/54144170-7775c480-442b-11e9-922a-9741beb4e706.png">

**Comment by schmidyy** [comment]
Thank you @NotFoundDC
