### ISSUE TITLE
textAlignment

### ISSUE THREAD

**Issue by MartinP7r** [schmidyy/Loaf#9]
Great library!  
It got mentioned on the Swift over coffee podcast, so I wanted to try it out.  
I didn't see it anywhere, but is it possible to customize the text further? Like setting the `textAlignment` to `.center` for example?

**Comment by schmidyy** [comment]
Thanks for checking it out!

`textAlignment` isn't customizable yet (everything will be left aligned for now), but i'll include this in my next release!

**Comment by schmidyy** [comment]
Added here: https://github.com/schmidyy/Loaf/commit/f4a5a91e6a4459d9217d0178673bfeeff5cd40f0
